### PR TITLE
Add publish plugin tusk

### PR DESCRIPTION
**Pull request by satamas**
We've recently added such functionality for TeamCity plugins on plugins.jetbrains.com side.

### CODE REVIEW

**Comment by rodm** [comment]
@satamas thanks for this PR. I've tried it out and it works well, however I had to add the following configuration to the `settings.gradle` file 

    pluginManagement {
        repositories {
            gradlePluginPortal()
            maven { url "http://dl.bintray.com/jetbrains/intellij-plugin-service" }
        }
    }

I had a look at the `intellij-plugin-service` package on Bintray and see that it is linked to jcenter but not all the files are available via jcenter, such as `structure-base` and `structure-teamcity`. Here is a link to the artifacts available on [jcenter](http://dl.bintray.com/bintray/jcenter/org/jetbrains/intellij/plugins/), and in the [intellij-plugin-service](http://dl.bintray.com/jetbrains/intellij-plugin-service/org/jetbrains/intellij/plugins/) repository.

Do you know why these other artifacts aren't available via jcenter? It would be useful if they were available then the above configuration would not be needed as Gradle searches jcenter for plugin dependencies. Should I raise this as an issue on the `intellij-plugin-verifier` project?

**Comment by satamas** [comment]
@rodm I've faced this issue also, but that wasn't clear for me why it works for intellij lib and doesn't work for TeamCity lib, because we are publishing them together. I thought that plugin dependencies are somehow published together with plugin to plugins portal.
I've wrote to person responsible for publishing, he will fix it soon.

**Comment by rodm** [comment]
@satamas thanks for passing the dependencies problem on. I've merged your changes and closed this PR.

**Comment by satamas** [comment]
@rodm it should be fixed now, please check.

**Comment by rodm** [comment]
@satamas checked and dependencies are resolving from jcenter, thanks.

**Pull request merged**
